// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4lmmwAGbERteMTD3bjLAONVk-FVm7O6M',
    appId: '1:1080933464873:web:e5906faabe0e69dfa7d538',
    messagingSenderId: '1080933464873',
    projectId: 'sigmaty-73444',
    authDomain: 'sigmaty-73444.firebaseapp.com',
    storageBucket: 'sigmaty-73444.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_1Ejq5-IzcbbiLouYOoYWd-G70KayFBs',
    appId: '1:1080933464873:android:344c1f61c6019a4da7d538',
    messagingSenderId: '1080933464873',
    projectId: 'sigmaty-73444',
    storageBucket: 'sigmaty-73444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsIzNLBQKM-ZKMd8s9rBEXkl8LGe5_G5k',
    appId: '1:1080933464873:ios:f01af08b06427f54a7d538',
    messagingSenderId: '1080933464873',
    projectId: 'sigmaty-73444',
    storageBucket: 'sigmaty-73444.appspot.com',
    iosBundleId: 'com.example.sigmaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4lmmwAGbERteMTD3bjLAONVk-FVm7O6M',
    appId: '1:1080933464873:web:ad610df8badbac4da7d538',
    messagingSenderId: '1080933464873',
    projectId: 'sigmaty-73444',
    authDomain: 'sigmaty-73444.firebaseapp.com',
    storageBucket: 'sigmaty-73444.appspot.com',
  );
}
